# Generated by Django 4.1.1 on 2022-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cities_contacts_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
